Improved portability of fai-pxe
On Mac OS X, sed does only supports alternation within regular
expressions if `sed -E` is used.  However, GNU sed does not recognize
the -E option.  Therefore, we use bash as a portable way to do string
manipulation.

The `mktemp --tmpdir` option is only supported by the mktemp in
coreutils >= 7.4 (available since Debian 6).  Neither the Mac OS X nor
the older mktemp in Linux supports --tmpdir, so we'll just leave it off.

Also downgraded failure of `git ls-remote` from a fatal error to a
warning.

diff --git a/SERVER-SIDE/bin/fai-pxe b/SERVER-SIDE/bin/fai-pxe
--- a/SERVER-SIDE/bin/fai-pxe
+++ b/SERVER-SIDE/bin/fai-pxe
@@ -21,7 +21,13 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 # current tag or branch
 if [ -d "`dirname "$SELF"`/../../.git" ]; then
     export GIT_DIR="`dirname "$SELF"`/../../.git"
-    git_ref=`git describe --all | sed -e 's,^heads/\|^tags/,,'`
+    git_ref=`git describe --all | while read i ; do
+                case "$i" in
+                    heads/*) echo "${i#heads/}" ;;
+                    tags/*)  echo "${i#tags/}"  ;;
+                    *)       echo "$i" ;;
+                esac
+            done`
 fi
 
 fai_chboot=/usr/sbin/fai-chboot
@@ -89,7 +95,7 @@ show_remote_commit() {
       1.0.*|1.1.*|1.2.*|1.3.*|1.4.*)
         tmp=`git ls-remote "$FAI_CONFIG_SRC" "${git_ref:-HEAD}"`
         if [ -z "$tmp" ]; then
-            echo "fatal: Remote branch $git_ref not found in upstream origin" >&2
+            echo "warning: Remote branch $git_ref not found in upstream origin" >&2
             echo "Maybe you forgot to \`git push\` your branch?" >&2
             exit 128
         else
@@ -100,7 +106,12 @@ show_remote_commit() {
 
       *)
         # Get a little more information than `git ls-remote`
-        tmp="`mktemp --tmpdir -d fai-pxe.XXXXX`"
+        tmp=`mktemp -d fai-pxe.XXXXX`
+        status=$?
+        if [ $status != 0 ]; then
+            echo "warning: Unable to create a temporary directory." >&2
+            exit $status
+        fi
         trap "rm -rf \"$tmp\"" EXIT
 
         [ -n "$git_ref" ] && checkout="-b $git_ref"
