Corrected template list in fai-pxe help message
Fixed the fai-pxe help message so that it can list the available PXE
templates even when running remotely.

diff --git a/SERVER-SIDE/bin/fai-pxe b/SERVER-SIDE/bin/fai-pxe
--- a/SERVER-SIDE/bin/fai-pxe
+++ b/SERVER-SIDE/bin/fai-pxe
@@ -16,7 +16,7 @@ case "$FAI_CONFIG_SRC" in
     FAI_CONFIG_SRC="${FAI_CONFIG_SRC#git+}"
     ;;
   *)
-    echo "ERROR: `basename $0` expects the FAI configuration to be stored in Git." >&2
+    echo "Error: `basename $0` expects the FAI configuration to be stored in Git." >&2
     exit 9
     ;;
 esac
@@ -30,6 +30,25 @@ if [ -d "`dirname "$SELF"`/../../.git" ]; then
     git_ref=`git describe --all | sed -e 's,^heads/\|^tags/,,'`
 fi
 
+fai_chboot=/usr/sbin/fai-chboot
+function auth() {
+    local hostname
+    hostname="$1"
+    if [ -x "`dirname $SELF`/../webcgi/auth" ]; then
+        LC_ALL=C "`dirname $SELF`/../webcgi/auth" "$hostname"
+    elif [ -x /var/www/fai/auth ]; then
+        LC_ALL=C /var/www/fai/auth "$hostname"
+    else
+        echo "NOTICE: Unable to pre-authorize host $hostname" >&2
+    fi
+}
+if [ ! -x "$fai_chboot" ]; then
+    fai_chboot="ssh root@$SERVER LC_ALL=C $fai_chboot"
+    function auth() {
+        echo "\`LC_ALL=C /var/www/fai/auth \"$1\"\`"
+    }
+fi
+
 help() {
     echo \
 "Usage: `basename $0` [-t TEMPLATE] [-r GIT_REF] HOSTNAME [HOSTNAME ...]
@@ -41,14 +60,13 @@ help() {
     Options:
 
       -t TEMPLATE
-          Specifies which PXE template to use.  Valid templates are:"
-    LC_ALL=C fai-chboot -lt | while read type name rest ; do echo \
+          Specifies which PXE template to use.
+
+          Available templates are:"
+    $fai_chboot -lt | while read type name rest ; do echo \
 "                ${name%.tmpl}"
     done
-    echo \
-"          If no template is specified, the host will be set to boot from
-          the local disk.
-
+    echo "
       -l
           Specifies that the host(s) should be set to boot from the local
           disk.
@@ -140,25 +158,6 @@ if [ -z "$localboot$template" ] || [ -n "$localboot" -a "$template" ]; then
     echo >&2
     help >&2
     exit 1
-fi
-
-fai_chboot=/usr/sbin/fai-chboot
-function auth() {
-    local hostname
-    hostname="$1"
-    if [ -x "`dirname $SELF`/../webcgi/auth" ]; then
-        LC_ALL=C "`dirname $SELF`/../webcgi/auth" "$hostname"
-    elif [ -x /var/www/fai/auth ]; then
-        LC_ALL=C /var/www/fai/auth "$hostname"
-    else
-        echo "NOTICE: Unable to pre-authorize host $hostname" >&2
-    fi
-}
-if [ ! -x "$fai_chboot" ]; then
-    fai_chboot="ssh root@$SERVER LC_ALL=C $fai_chboot"
-    function auth() {
-        echo "\`LC_ALL=C /var/www/fai/auth \"$1\"\`"
-    }
 fi
 
 if [ -n "$localboot" ]; then
