Imported updated scripts from FAI-CD 5.1.2
Copied DEBIAN scripts as DEB_BASED so that they also apply to UBUNTU.

diff --git a/scripts/FAIBASE/10-misc b/scripts/FAIBASE/10-misc
--- a/scripts/FAIBASE/10-misc
+++ b/scripts/FAIBASE/10-misc
@@ -1,42 +1,27 @@
 #! /bin/bash
 
-# (c) Thomas Lange, 2001-2007, lange@debian.org
+# (c) Thomas Lange, 2001-2012, lange@debian.org
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
-# a list of modules which are loaded at boot time
-fcopy -iBM /etc/modules
-for module in $MODULESLIST; do
-    ainsl -a $target/etc/modules "^$module$"
-done
-
-# disable fsck on ext3 filesystems
-for part in $(mount|grep $target |grep "type ext3"|perl -ane 'print "$F[0] "')
-do
-    echo "Disable periodic fsck on $part"
-    tune2fs -c 0 -i 0 $part
-done
-
-fcopy /etc/hostname || echo $HOSTNAME     > $target/etc/hostname
 echo $TIMEZONE    > $target/etc/timezone
-ln -fs /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
+cp -f /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
 
-fcopy -iBM /etc/hosts /etc/motd
+if [ -n "$IPADDR" ]; then
+    ifclass DHCPC || ainsl -s /etc/hosts "$IPADDR $HOSTNAME.$DOMAIN $HOSTNAME"
+else
+    ifclass DHCPC && ainsl -s /etc/hosts "127.0.0.1 $HOSTNAME"
+fi
 
-# set root password
-echo "root:$ROOTPW" | $ROOTCMD chpasswd --encrypted
+fcopy -iM /etc/hosts /etc/motd
+
 # make /root accessible only by root
-chmod 0700 $target/root
-chown root:root $target/root
+chmod -c 0700 $target/root
+chown -c root:root $target/root
 # copy default dotfiles for root account
-fcopy -iBMr /root
+fcopy -ir /root
 
-# create keyboard layout table
-$ROOTCMD bash -c "echo 'console-data console-data/keymap/full select $KEYMAP' | debconf-set-selections"
-$ROOTCMD install-keymap $KEYMAP || true
-# dumpkeys | gzip -9f >$target/etc/console/boottime.kmap.gz
-
-# ChrisD says: here's a dumping ground.
-fcopy -iBM /etc/X11/xorg.conf
+chmod -c 1777 ${target}/tmp
+chown -c 0:0  ${target}/tmp
 
 exit $error
diff --git a/scripts/LAST/50-misc b/scripts/LAST/50-misc
--- a/scripts/LAST/50-misc
+++ b/scripts/LAST/50-misc
@@ -1,17 +1,39 @@
 #! /bin/bash
 
-# copyright Thomas Lange 2001-2007, lange@debian.org
+# copyright Thomas Lange 2001-2015, lange@debian.org
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
-# remove backup files from cfengine
-dirs="root etc var"
-for path in $dirs; do
-    find $target/$path -maxdepth 20 -name \*.cfedited -o -name \*.cfsaved | xargs -r rm
-done
+if [ "$FAI_ACTION" = "dirinstall" ] ; then
+  :
+else
+  # check if mdadm has been forgotten
+  if grep -q active /proc/mdstat 2>/dev/null; then
+    if [ ! -d $target/etc/mdadm ]; then
+	echo ERROR: Found Software RAID, but the mdadm package was not installed
+	error=1
+    fi
+  fi
 
-[ "$FAI_DEBMIRROR" ] && 
-echo "#$FAI_DEBMIRROR $MNTPOINT nfs ro 0 0" >> $target/etc/fstab
+  usedm=$(dmsetup ls | egrep -v '^live-rw|^live-base|^No devices found' | wc -l)
+  if [ $usedm -ne 0 ]; then
+    if [ ! -d $target/etc/lvm ]; then
+	echo ERROR: Found lvm devices, but the lvm2 package was not installed
+	error=1
+    fi
+  fi
+fi
+
+# remove backup files from cfengine, but only if cfengine is installed
+if [ -x /usr/sbin/cfagent ] || [ -x $target/usr/sbin/cfagent ] ; then
+    dirs="root etc var"
+    for path in $dirs; do
+        find $target/$path -maxdepth 20 -name \*.cfedited -o -name \*.cfsaved | xargs -r rm
+    done
+fi
+
+[ "$FAI_DEBMIRROR" ] &&
+  ainsl /etc/fstab "#$FAI_DEBMIRROR $MNTPOINT nfs ro 0 0"
 
 # set bios clock
 if [ $do_init_tasks -eq 1 ] ; then
@@ -19,17 +41,21 @@ if [ $do_init_tasks -eq 1 ] ; then
        no|"") hwopt="--localtime" ;;
        yes)   hwopt="--utc"       ;;
     esac
-    $ROOTCMD hwclock $hwopt --systohc || true
+    hwclock $hwopt --systohc || true
 fi
 
 # Make sure everything is configured properly
-echo "Running \"apt-get -f install\" for the last time."
-$ROOTCMD apt-get -f --no-remove install < /dev/null
+if ifclass DEBIAN ; then
+        echo "Running \"apt-get -f install\" for the last time."
+        $ROOTCMD apt-get -f install
+fi
 
-lskernels=$(echo $target/boot/vmlinu*)
-[ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log"
+if [ $FAI_ACTION = "install" ]; then
+    lskernels=$(echo $target/boot/vmlinu*)
+    [ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
+fi
+
 # copy sources.list
-fcopy -iBM /etc/apt/sources.list
+fcopy -iM /etc/apt/sources.list
 
 exit $error
-
