CENTOS GRUB fix
Use a more sophisticated way to determine which disk(s) to install GRUB
on.  Don't assume that if /dev/md0 exists then we want to install GRUB
to the first two disks, and that if it's not a DISK2 installation then
we want to install to the first disk.  Rather, try to determine the
physical disk(s) on which the boot partition resides (unless the DISK2
class applies, in which case we install to the first two disks).

Always install lvm2 on CENTOS_7, since all of our partitioning schemes
use it.  Without it, dracut would generate an initrd without LVM
support.

diff --git a/scripts/GRUB2/50-setup b/scripts/GRUB2/50-setup
--- a/scripts/GRUB2/50-setup
+++ b/scripts/GRUB2/50-setup
@@ -1,47 +1,75 @@
 #! /bin/bash
 
-[ $do_init_tasks -eq 1 ] || exit 0
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
 . /usr/lib/fai/subroutines
 
-error=0 ; trap "error=$((error|1))" ERR
+# Find the physical devices on which the given partitions reside, tracing
+# through MD and LVM layers if necessary.
+resolve_to_phys_dev() {
+    stat -L --format '%t %T %n' $@ | while read -r major_hex minor_hex dev ; do
+        major=$((0x$major_hex))
+        minor=$((0x$minor_hex))
+        if [ -f "/sys/dev/block/$major:$minor/partition" ]; then
+            partition=$(cat "/sys/dev/block/$major:$minor/partition")
+            minor=$(($minor - $partition))
+            dev=${dev%$partition}
+        fi
+        if [ -e "/sys/dev/block/$major:$minor/device" ]; then
+            # This is a physical device
+            echo "$dev"
+        elif [ -d "/sys/dev/block/$major:$minor/slaves" ]; then
+            # This is a MD or LVM member
+            for slave in /sys/dev/block/$major:$minor/slaves/* ; do
+                resolve_to_phys_dev "/dev/$(basename $slave)"
+            done
+        fi
+    done | sort -u
+}
 
-######################################################
-
-if [ X$FAI_ACTION = Xdirinstall ]; then
+if [ "$FAI_ACTION" = dirinstall ]; then
+    # TODO: How can we determine the boot disks for a dirinstall?
+    # Should we even try?
     set_disk_info
+else
+    . $LOGDIR/disk_var.sh
 fi
 
-# Using md0 and first one or two disks should be correct. fai/config/disk_config/??? sets these.
-if [ -b /dev/md0 ]; then
-    bootdisks=$(echo $disklist | awk '{print $1 " " $2}')
-elif ifclass DISK2 ; then
+if ifclass DISK2 ; then
     for disk in $disklist; do
         dd if="/dev/$disk" of="$target/root/bootsect-backup.$disk" bs=512 count=1
     done
-    bootdisks=$(echo $disklist | awk '{print $1 " " $2}')
+    bootdisks=$(echo $disklist | awk '{printf "/dev/%s /dev/%s", $1, $2}')
+elif [ -n "$BOOT_DEVICE" ]; then
+    bootdisks=$(resolve_to_phys_dev "$BOOT_DEVICE")
+    echo "Resolved $BOOT_DEVICE to disks: $bootdisks"
 else
-    bootdisks=$(echo $disklist | awk '{print $1}')
+    echo "ERROR: Boot disk could not be determined"
+    exit 1
 fi
 
-set -x
-for i in $bootdisks ; do
+for disk in $bootdisks ; do
     # Try the bios_grub flag for GPT partition tables, then the boot flag for
     # MBR partition tables.
     # The "1" in parted and dd -MUST- correspond with fai/config/disk_config/???
-    parted -s /dev/${i} set 1 bios_grub on || \
-    parted -s /dev/${i} set 1 boot on || \
-    sleep 3686
-
+    parted -s "$disk" set 1 bios_grub on || \
+    parted -s "$disk" set 1 boot on
 
     GRUBEXTRA=""
     # Found IBM HS20 Blades with IDE disk.
     /usr/bin/lspci | grep -q "IDE interface: Broadcom CSB5 IDE Controller" && GRUBEXTRA=" --modules=ata"
 
-    $ROOTCMD /usr/sbin/grub-install $GRUBEXTRA --no-floppy /dev/${i}
-done
-set +x
+    if $ROOTCMD which /usr/sbin/grub2-install >/dev/null 2>&1; then
+        $ROOTCMD /usr/sbin/grub2-install $GRUBEXTRA --no-floppy "$disk"
+    else
+        $ROOTCMD /usr/sbin/grub-install $GRUBEXTRA --no-floppy "$disk"
+    fi
 
-$ROOTCMD /usr/sbin/update-grub
+    if [ $? = 0 ]; then
+        echo "Installed GRUB on $disk"
+    else
+        echo "ERROR: Failed to install GRUB on $disk"
+    fi
+done
 
 exit $error
